version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es-net
    ports:
      - 9201:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [
        'CMD-SHELL',
        'curl -s -X GET "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s&pretty" | grep -q "\"status\" : \"green\""'
      ]
      timeout: 30s
      interval: 30s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
      - SERVER_HOST=0.0.0.0
    networks:
      - es-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5602:5601
networks:
  es-net:
    driver: bridge
volumes:
  esdata:
    driver: local
